### ISSUE TITLE
Obtuse error when opening rom for the first time after turning on snes

### ISSUE THREAD

**Issue by melink14** [tcprescott/RomLoader#1]
I turn on my snes and then open a rom and get this output:

```
Attaching to first device found.
Attached to device "COM5"
----------------------------
0 - default
1 - SuperMarioRPG
What destination (enter to chose 0)?

getting list of /alttpr/transferred to verify path exists
Traceback (most recent call last):
  File "romloader.py", line 137, in <module>
  File "romloader.py", line 99, in main
  File "py2snes\__init__.py", line 205, in List
  File "py2snes\__init__.py", line 264, in _list
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Press key to exit.
```

I can fix this by simply opening the file viewer app that came with usb2snes.

**Comment by tcprescott** [comment]
I was able to reproduce it.  It appears to be a problem with Redguyy's usb2snes websocket server.  Sometimes, the List operation doesn't return any data when it should return data.  I'm going to add a retry with backoff on the List function to workaround it.

Qusb2snes (a Qt rewrite of the websocket server) works pretty well and could be used until I fix this.

https://github.com/Skarsnik/QUsb2snes/releases

**Comment by melink14** [comment]
Thanks, I'll check out Qusb2snes as well. It's amazing how much interesting work is going around x2snes that seems to be scattered around the web.

**Comment by tcprescott** [comment]
@melink14 - My latest release on RomLoader should fix this (1.1.4).

https://github.com/tcprescott/RomLoader/releases/tag/1.1.4

Could you let me know if you're running into other issues?

**Comment by melink14** [comment]
Thanks. I'll update later today. I switched to qusb2snes earlier (which was great after reporting some early issues) so the rom loader has been great either way!

**Comment by tcprescott** [comment]
You may want to use 1.1.5, I accidentally broke some things by adding a retry.
